########################################################################################################################
# Global configuration - (TO REFACTOR)
########################################################################################################################
env=PROD

ORG.url=https://zebrunner.org
ORG.base=https://orgautomation.zebrunner.org

DEV.url=https://zebrunner.dev
DEV.base=https://devtests.zebrunner.dev

PROD.url=https://zebrunner.com
PROD.base=https://automationzbr.zebrunner.com

ONPREM.url=https://zebrunner.dev
ONPREM.base=https://onprem.zebrunner.dev

########################################################################################################################
# Carina webdriver configuration - (DO NOT REMOVE IF NOT NECESSARY)
########################################################################################################################
selenium_url=http://localhost:4444/wd/hub
page_opening_strategy=BY_ELEMENT
capabilities.browserName=chrome
capabilities.browserVersion=NULL
capabilities.zebrunner\:enableVNC=true
capabilities.zebrunner\:enableVideo=true
auto_screenshot=true

########################################################################################################################
# Webdriver configuration - (DO NOT REMOVE IF NOT NECESSARY)
########################################################################################################################
implicit_timeout=40
explicit_timeout=40
retry_interval=100
auto_download=true

########################################################################################################################
# Report configuration
########################################################################################################################
core_log_level=INFO
keep_all_screenshots=FALSE
project_report_directory=./reports/qa
report_url=NULL
max_screen_history=10
result_sorting=true

########################################################################################################################
# Retry configuration
########################################################################################################################
init_retry_count=0
init_retry_interval=1
retry_count=0
