# Use only for local development

test.user.admin.username=
test.user.admin.password=

test.user.test-user.username=
test.user.test-user.password=

########################################################################################################################
# GMAIL
########################################################################################################################
test.email-account.username=
test.email-account.password=

########################################################################################################################
# GitHub
########################################################################################################################
test.external-service.github.url=
test.external-service.github.username=
test.external-service.github.access-token=

########################################################################################################################
# GitLab
########################################################################################################################
test.external-service.gitlab.username=
test.external-service.gitlab.access-token=

########################################################################################################################
# Bitbucket
########################################################################################################################
test.external-service.bitbucket.username=
test.external-service.bitbucket.access-token=

########################################################################################################################
# BrowserStack
########################################################################################################################
test.external-service.browser-stack.hub-url=
test.external-service.browser-stack.username=
test.external-service.browser-stack.access-key=

########################################################################################################################
# SauceLabs
########################################################################################################################
test.external-service.sauce-labs.hub-url=
test.external-service.sauce-labs.username=
test.external-service.sauce-labs.access-key=

########################################################################################################################
# LambdaTest
########################################################################################################################
test.external-service.lambda-test.hub-url=
test.external-service.lambda-test.username=
test.external-service.lambda-test.access-key=

########################################################################################################################
# Jira
########################################################################################################################
test.external-service.jira.url=
test.external-service.jira.username=
test.external-service.jira.token=

########################################################################################################################
# Slack
########################################################################################################################
test.external-service.slack.bot-name=
test.external-service.slack.token=

########################################################################################################################
# TestRail
########################################################################################################################
test.external-service.test-rail.url=
test.external-service.test-rail.username=
test.external-service.test-rail.password=
